server:
  servlet:
    context-path: /youtest
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://101.133.232.238:3306/youtest?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ENC(B9yhDfdvAiqLcZZqWUgvfw==)
    password: ENC(wdRCXFmldZsX4vuXPUO1cq+vvc++B9R/)
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info
    com.lilith.youtest.mapper: trace

jasypt:
  encryptor:
    password: youtest