server:
  servlet:
    context-path: /youtest
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youtest?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver